### ISSUE TITLE
pact-provider-verifier throwing error "undefined method `strip' for Pact::Term"

### ISSUE THREAD

**Issue by khansen** [SEEK-Jobs/pact-net#115]
PactNet version: PactNet.Windows.2.0.17

I have an interaction (generated by pact-js version 3.0.1, targeting specification version 2.0.0) which defines a regex matcher for the Authorization header:

```
      "request": {
        "method": "GET",
        "path": "/programs/33",
        "headers": {
          "Authorization": "A"
        },
        "matchingRules": {
          "$.headers.Authorization": {
            "match": "regex",
            "regex": "A|B"
          }
        }
      },
```

This is causing the following failure from PactVerifier.Verify():

```
Failure/Error: replay_interaction interaction

     NoMethodError:
       undefined method `strip' for #<Pact::Term:0x476c490 @generate="A", @matcher=/A|B/>
```

No further backtrace.
I'm guessing this is a problem in the Ruby verifier itself, not with PactNet, but I've not been able to track down where this strip call is performed in the verifier or supporting gems.

A similar matcher in the response body works as expected:

```
      "response": {
        "status": 200,
        "headers": {
          "Content-Type": "application/json; charset=utf-8"
        },
        "body": {
          "id": 33,
          "name": "F"
        },
        "matchingRules": {
          "$.body.name": {
            "match": "regex",
            "regex": "F|M"
          }
        }
      }
```

Any ideas on what could be going wrong with header matching? Tips for debugging the Ruby verifier (to get a proper backtrace) would also be appreciated.

**Comment by bethesque** [comment]
The way to recreate the issues without the .net code is to use the ruby-standalone-e2e-example codebase. I've attempted to recreate your issue here, but haven't succeeded. https://github.com/pact-foundation/pact-ruby-e2e-example/commit/8fea24c36ebf0840114f6e94f9520056b2f23507

Can you have a look at it and see if you can tell me what about my code doesn't match your scenario? I know it's Ruby, but hopefully it's readable enough!

Perhaps it's to do with the version of the standalone package that .net is using. @neilcampbell what version are you on?

**Comment by khansen** [comment]
@bethesque Thanks, I made some good progress on this.
Managed to get a backtrace by changing
```
            :backtrace => false,
```
to
```
            :backtrace => true,
```
in pact-provider-verifier\lib\pact\provider_verifier\app.rb (too bad this isn't configurable).

```
NoMethodError:
       undefined method `strip' for #<Pact::Term:0x4840800 @generate="A", @matcher=/A|B/>
     # ./pact-win32/lib/ruby/lib/ruby/2.2.0/net/http/header.rb:17:in `block in initialize_http_header'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/rack-2.0.3/lib/rack/utils.rb:454:in `block in each'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/rack-2.0.3/lib/rack/utils.rb:453:in `each'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/rack-2.0.3/lib/rack/utils.rb:453:in `each'
     # ./pact-win32/lib/ruby/lib/ruby/2.2.0/net/http/header.rb:15:in `initialize_http_header'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/rack-reverse-proxy-0.12.0/lib/rack_reverse_proxy/roundtrip.rb:105:in `initialize_http_header'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/rack-reverse-proxy-0.12.0/lib/rack_reverse_proxy/roundtrip.rb:189:in `setup_request'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/rack-reverse-proxy-0.12.0/lib/rack_reverse_proxy/roundtrip.rb:208:in `proxy'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/rack-reverse-proxy-0.12.0/lib/rack_reverse_proxy/roundtrip.rb:21:in `call'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/rack-reverse-proxy-0.12.0/lib/rack_reverse_proxy/middleware.rb:25:in `call'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/rack-test-0.6.3/lib/rack/mock_session.rb:30:in `request'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/rack-test-0.6.3/lib/rack/test.rb:244:in `process_request'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/rack-test-0.6.3/lib/rack/test.rb:58:in `get'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/pact-1.16.0/lib/pact/provider/test_methods.rb:23:in `replay_interaction'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/pact-1.16.0/lib/pact/provider/rspec.rb:84:in `block (4 levels) in describe_interaction'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/pact-1.16.0/lib/pact/provider/rspec.rb:174:in `run_once'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/pact-1.16.0/lib/pact/provider/rspec.rb:81:in `block (3 levels) in describe_interaction'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example.rb:447:in `instance_exec'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example.rb:447:in `instance_exec'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/hooks.rb:350:in `run'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/hooks.rb:507:in `block in run_owned_hooks_for'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/hooks.rb:506:in `each'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/hooks.rb:506:in `run_owned_hooks_for'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/hooks.rb:593:in `block in run_example_hooks_for'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/hooks.rb:592:in `reverse_each'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/hooks.rb:592:in `run_example_hooks_for'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/hooks.rb:462:in `run'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example.rb:494:in `run_before_example'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example.rb:253:in `block in run'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example.rb:500:in `block in with_around_and_singleton_context_hooks'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example.rb:457:in `block in with_around_example_hooks'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/hooks.rb:464:in `block in run'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/hooks.rb:602:in `run_around_example_hooks_for'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/hooks.rb:464:in `run'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example.rb:457:in `with_around_example_hooks'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example.rb:500:in `with_around_and_singleton_context_hooks'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example.rb:251:in `run'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:627:in `block in run_examples'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:623:in `map'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:623:in `run_examples'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:589:in `run'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:590:in `block in run'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:590:in `map'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:590:in `run'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:590:in `block in run'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:590:in `map'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:590:in `run'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:590:in `block in run'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:590:in `map'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:590:in `run'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:590:in `block in run'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:590:in `map'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:590:in `run'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:118:in `block (3 levels) in run_specs'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:118:in `map'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:118:in `block (2 levels) in run_specs'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:1894:in `with_suite_hooks'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:113:in `block in run_specs'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/reporter.rb:79:in `report'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:112:in `run_specs'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:87:in `run'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:71:in `run'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/pact-1.16.0/lib/pact/provider/pact_spec_runner.rb:94:in `run_specs'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/pact-1.16.0/lib/pact/provider/pact_spec_runner.rb:35:in `run'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/pact-1.16.0/lib/pact/cli/run_pact_verification.rb:60:in `run_with_pact_uri'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/pact-1.16.0/lib/pact/cli/run_pact_verification.rb:48:in `run_specs'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/pact-1.16.0/lib/pact/cli/run_pact_verification.rb:22:in `call'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/pact-1.16.0/lib/pact/cli/run_pact_verification.rb:14:in `call'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.6.0/lib/pact/provider_verifier/app.rb:105:in `verify_pact'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.6.0/lib/pact/provider_verifier/app.rb:28:in `block in call'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.6.0/lib/pact/provider_verifier/app.rb:27:in `collect'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.6.0/lib/pact/provider_verifier/app.rb:27:in `call'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.6.0/lib/pact/provider_verifier/app.rb:21:in `call'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.6.0/lib/pact/provider_verifier/cli/verify.rb:24:in `verify'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
     # ./pact-win32/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.6.0/lib/pact/provider_verifier/cli/custom_thor.rb:17:in `start'
     # ./pact-win32/lib/app/pact-provider-verifier.rb:2:in `<main>'
```
Got the log from pact/lib/pact/provider/test_methods.rb replay_interaction:
```
Sending GET request to path: "/programs/33" with headers: {"HTTP_AUTHORIZATION"=>#<Pact::Term:0x3d78e00 @generate="A", @matcher=/A|B/>}
```
Uh-oh, looks like header terms are not expanded ("reified") to a string the same way the query and body are.

If I change the headers implementation in pact\lib\pact\provider\request.rb like this (inspired by reified_body):
```
        def headers
          request_headers = {}
          return request_headers if expected_request.headers.is_a?(Pact::NullExpectation)
          expected_request.headers.each do |key, value|
            request_headers[rack_request_header_for(key)] = reified_value(value)
          end
          request_headers
        end

        def reified_value value
          case value
          when String then value
          when NullExpectation then ''
          else
            rb = Pact::Reification.from_term(value)
            if rb.is_a?(String)
              rb
            else
              JSON.dump(rb)
            end
          end
        end
```
... the verification succeeds.
Makes sense? (body / reified_body could be refactored to call reified_value(expected_request.body). Not sure where query reification is done, but I tested that it works.)

**Comment by khansen** [comment]
@bethesque @neilcampbell PactNet is on standalone version 1.4.4; I've tested with the latest (1.9.0) and the issue persists.

**Comment by bethesque** [comment]
Sorry, this got automatically closed by my commit message. Please reopen it until we've gotten the fix into the .net package.

**Comment by bethesque** [comment]
@neilcampbell can you update the standalone version to 1.9.1 please. There are some changes to the CLI, but they're backwards compatible, so you can just upgrade for now, and then make the changes later.

**Comment by neilcampbell** [comment]
@bethesque Yep sure can.

**Comment by neilcampbell** [comment]
I have updated to 1.9.1 and pushed the package to the Nuget feed, however Nuget is currently experiencing a service degradation, so it cannot be downloaded just yet. Hopefully will be fixed soon. https://status.nuget.org/

**Comment by neilcampbell** [comment]
Everything appears to be good now.

**Comment by khansen** [comment]
Verified fixed in latest Nuget. Great work, @bethesque and @neilcampbell !

The verifier is giving the warning
```
WARN: The --pact-urls option is deprecated. Please pass in a space separated list of URLs as the first arguments to the pact-provider-verifier command.
```
As mentioned in https://github.com/SEEK-Jobs/pact-net/issues/116, there's a change required to PactVerifierHostConfig Arguments to get rid of that.
